# Generated by Django 6.0.5 on 2026-06-04 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ تراکنش (ریال)')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'پرداخت موفق'), ('failed', 'پرداخت ناموفق'), ('canceled', 'لغو شده توسط کاربر')], default='pending', max_length=20, verbose_name='وضعیت تراکنش')),
                ('gateway', models.CharField(max_length=50, verbose_name='درگاه پرداخت')),
                ('authority', models.CharField(blank=True, max_length=255, null=True, verbose_name='کد اتوریتی / توکن درگاه')),
                ('ref_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='شماره پیگیری بانک (RefID)')),
                ('gateway_response', models.TextField(blank=True, null=True, verbose_name='پاسخ کامل درگاه (Log)')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید پرداخت بانک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تراکنش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'تراکنش پرداخت',
                'verbose_name_plural': 'تراکنش\u200cهای پرداخت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['authority'], name='payments_pa_authori_d17c7e_idx')],
            },
        ),
    ]
