# Generated by Django 6.0.5 on 2026-06-04 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_order_orders_orde_status_079368_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان / مناسبت')),
                ('type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed_amount', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار تخفیف (درصد یا ریال)')),
                ('max_discount', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='سقف تخفیف (ریال) - مخصوص درصدی')),
                ('min_order_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حداقل مبلغ سفارش برای اعمال کد (ریال)')),
                ('max_usage', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد دفعات استفاده کل')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دفعات استفاده شده')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع اعتبار')),
                ('expire_at', models.DateTimeField(verbose_name='تاریخ انقضا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'start_date', 'expire_at'], name='discounts_c_is_acti_77c664_idx')],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ تخفیف کسر شده (ریال)')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان استفاده')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.coupon', verbose_name='کد تخفیف')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='orders.order', verbose_name='سفارش مربوطه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر استفاده\u200cکننده')),
            ],
            options={
                'verbose_name': 'تاریخچه استفاده از تخفیف',
                'verbose_name_plural': 'تاریخچه\u200cهای استفاده از تخفیف',
                'indexes': [models.Index(fields=['coupon', 'user'], name='discounts_c_coupon__fcc2f5_idx')],
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
