# Generated by Django 6.0.5 on 2026-06-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام ویژگی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ (URL)')),
                ('type', models.CharField(choices=[('text', 'متنی'), ('color', 'رنگ'), ('number', 'عددی')], default='text', max_length=20, verbose_name='نوع ویژگی')),
                ('is_filterable', models.BooleanField(default=True, verbose_name='قابل فیلتر است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی\u200cها',
                'indexes': [models.Index(fields=['is_filterable'], name='variants_at_is_filt_010224_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='مقدار')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ (URL)')),
                ('color_code', models.CharField(blank=True, help_text='کد هگزادسیمال رنگ مثل #FFFFFF', max_length=7, null=True, verbose_name='کد رنگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='variants.attribute', verbose_name='ویژگی مربوطه')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='شناسه کالا (SKU)')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='بارکد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت اصلی (ریال/تومان)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت با تخفیف')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('weight', models.PositiveIntegerField(blank=True, help_text='وزن مخصوص این تنوع به گرم', null=True, verbose_name='وزن')),
                ('image', models.ImageField(blank=True, null=True, upload_to='variants/', verbose_name='تصویر اختصاصی تنوع')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تنوع محصول',
                'verbose_name_plural': 'تنوع\u200cهای محصولات',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.attributevalue', verbose_name='مقدار ویژگی')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='variants.productvariant', verbose_name='تنوع محصول')),
            ],
            options={
                'verbose_name': 'ویژگی تنوع محصول',
                'verbose_name_plural': 'ویژگی\u200cهای تنوع\u200cهای محصولات',
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attribute_values',
            field=models.ManyToManyField(related_name='variants', through='variants.VariantAttributeValue', to='variants.attributevalue', verbose_name='ویژگی\u200cهای این تنوع'),
        ),
        migrations.AddIndex(
            model_name='variantattributevalue',
            index=models.Index(fields=['attribute_value', 'variant'], name='variants_va_attribu_15849b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together={('variant', 'attribute_value')},
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active'], name='variants_pr_is_acti_ca6f9b_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='variants_pr_price_c74a9a_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['is_active', 'stock_quantity'], name='variants_pr_is_acti_0596da_idx'),
        ),
    ]
