# Generated by Django 6.0.5 on 2026-06-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت با تخفیف'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت اصلی (ریال/تومان)'),
        ),
    ]
