# Generated by Django 6.0.5 on 2026-06-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='نام آدرس'),
            preserve_default=False,
        ),
    ]
