# Generated by Django 6.0.5 on 2026-06-04 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_last_name_address'),
        ('variants', '0002_alter_productvariant_discount_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده / در حال پردازش'), ('shipped', 'تحویل به پست / ارسال شده'), ('delivered', 'تحویل داده شده'), ('canceled', 'لغو شده'), ('refunded', 'مرجوع شده')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد رهگیری پستی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کاربر / ادمین')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مجموع قیمت اقلام')),
                ('shipping_price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ارسال')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ تخفیف کد')),
                ('final_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ قابل پرداخت نهایی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر وضعیت')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address', verbose_name='نشانی ارسال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت واحد در لحظه خرید')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت کل این آیتم')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش مربوطه')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='variants.productvariant', verbose_name='تنوع محصول خریده شده')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
    ]
